#!/bin/bash

rotate() {
	local log_file=$1
	local maxbytes=$2
	local rotate=$3

	if [ $(du -sb $LOG_FILE) > $maxbytes ]
	then
		if [ -f $log_file.$rotate.gz ]
		then
	    		rm $log_file.$rotate.gz
  		fi
	
		i=1
		while [[ $i -le $rotate ]]
		do
			if [ -f $log_file.$i.gz ]
			then
				mv $log_file.$i.gz $log_file.$(($i+1)).gz
    			fi
			let i=$i+1
  		done
	
		gzip -c $LOG_FILE > $LOG_FILE"."1.gz
	fi
}

if [ -f ./backup_dir.ini ]	
then
	. ./backup_dir.ini
elif [ -f /etc/backup_dir/backup_dir.ini ]
then
        . /etc/backup_dir/backup_dir.ini
else
	logger "backup_dir could not find /etc/backup_dir/backup_dir.ini \
			or backup_dir.ini"
	exit 1
fi

logger "backup_dir create $(dirname LOG_FILE)"
[ -d $(dirname $LOG_FILE) ] || \
	logger "backup_dir $(mkdir -p $(dirname $LOG_FILE))" && exit 1

[ -w $LOG_FILE ] || logger "can't write to $LOG_FILE" && exit 1

if [ -f ./backup_dir ]	
then
	. EXEC="./backup_dir"
elif [ -f /usr/sbin/backup_dir ]
then
        . EXEC="/usr/sbin/backup_dir"
else
	logger "backup_dir could not find /usr/sbin/backup_dir or backup_dir"
	exit 1
fi

$EXEC >> $LOG_FILE || \
	mail -s "[$HOSTNAME] backup_dir failed" -a $LOG_FILE -r $FROM_MAIL $MAIL && exit 1

exit 0
